### ISSUE TITLE
Error: EISDIR: illegal operation on a directory on LinuxMint

### ISSUE THREAD

**Issue by marcoancona** [nathanbuchar/electron-settings#100]
One of our users is affected by the following problem on Linux Mint 18.2 Sonya. We use `electron-settings` 3.1.1 with default configuration.

```
Error: EISDIR: illegal operation on a directory, open '/home/kai/.config/MineTime/Settings'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1326:33)
    at Object.writeFileSync (/opt/MineTime/resources/app.asar/node_modules/electron-settings/node_modules/jsonfile/index.js:117:13)
    at Settings._ensureSettings (/opt/MineTime/resources/app.asar/node_modules/electron-settings/lib/settings.js:179:18)
    at Settings._readSettings (/opt/MineTime/resources/app.asar/node_modules/electron-settings/lib/settings.js:218:10)
    at Settings._getValueAtKeyPath (/opt/MineTime/resources/app.asar/node_modules/electron-settings/lib/settings.js:306:22)
    at Settings.get (/opt/MineTime/resources/app.asar/node_modules/electron-settings/lib/settings.js:428:17)
    at Object.<anonymous> (/opt/MineTime/resources/app.asar/dist/main/backend.js:1:2740) 
```

**Comment by nathanbuchar** [comment]
Hi @marcoancona,

as the first troubleshooting step, is your app running all electron-settings methods *within* `app.on('ready', ...)`?

For example:

```js
// wrong

const { app } = require('electron');
const settings = require('electron-settings');

settings.set('foo', 'bar');

app.on('ready', () => {
  console.log(`the value of foo is "${settings.get('foo')}"`);
});
```

```js
// right

const { app } = require('electron');
const settings = require('electron-settings');

app.on('ready', () => {
  settings.set('foo', 'bar');
  
  console.log(`the value of foo is "${settings.get('foo')}"`);
});
```

**Comment by marcoancona** [comment]
Oh, this might indeed be the issue. I would put a note about this requirements in the main README, because many might not reach the FAQs given that the API is quite self-explanatory.

**Comment by nathanbuchar** [comment]
I totally agree!

**Comment by nathanbuchar** [comment]
I'm going to mark this as complete. If you're still seeing problems, let me know
