### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: settings.anyMethod is not a function

### ISSUE THREAD

**Issue by DManstrator** [nathanbuchar/electron-settings#130]
Hello,

I'm currently updating Electron Settings from 3.2.0 to 4.0.1 and I got many issues. I was able to update my codebase based on the docs but when I'm trying to call any method, I get that UnhandledPromiseRejectionWarning telling me something is not a function where it should be.

Part of my code:
```js
const settings = require('electron-settings');
// ...

function createWindow() {
    // default
    let version = "v0.1";
    // ...
    console.log(settings);
    settings.configure({
        dir: __dirname,
        fileName: 'settings.json'
    });
    const exists = settings.hasSync('test');
    console.log(exists);
    if (settings.hasSync('version'))  {
        version = settings.getSync('version');
    }
    // ...
}
```
Full output (example):
```log
$ npm start

> TestProject@0.0.1 start <<Path>>\src\main\electron
> electron .


{
  default: {
    file: [Function: file],
    configure: [Function: configure],
    reset: [Function: reset],
    has: [Function: has],
    hasSync: [Function: hasSync],
    get: [Function: get],
    getSync: [Function: getSync],
    set: [Function: set],
    setSync: [Function: setSync],
    unset: [Function: unset],
    unsetSync: [Function: unsetSync]
  }
}
(node:4308) UnhandledPromiseRejectionWarning: TypeError: settings.configure is not a function
    at createWindow (<<Path>>\src\main\electron\main.js:43:14)
(node:4308) UnhandledPromiseRejectionWarning: TypeError: settings.configure is not a function
    at createWindow (<<Path>>\src\main\electron\main.js:43:14)
(node:4308) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4308) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4308) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:4308) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I think I made a tiny mistake but I'm not able to figure out.. I hope that you can help me.

**Comment by mferris77** [comment]
I'm having the same issue - for one, if I try to use 'import' I get an error in my main.js file.  If I try to instead 'require' it, I get the same set of errors as above.

**Comment by nathanbuchar** [comment]
Thanks for the notes all, I'll take a look this weekend!

**Comment by nathanbuchar** [comment]
Ah, looks like this is exporting a `default` object. The export target is wrong, whoops! Fixing now

**Comment by nathanbuchar** [comment]
Should be now fixed in v4.0.2!

**Comment by DManstrator** [comment]
Thanks for the quick response, works like a charm right now! :)

**Comment by nathanbuchar** [comment]
Beautiful, thanks for following up
