### ISSUE TITLE
npm test fails

### ISSUE THREAD

**Issue by black-snow** [nathanbuchar/electron-settings#45]
This is what happens when I run `npm test`:

```shell
npm test

> electron-settings@2.2.2 test /Users/Shared/EasyPhotoSync/windows/node_modules/electron-settings
> npm run test:main && npm run test:renderer


> electron-settings@2.2.2 test:main /Users/Shared/x/y/node_modules/electron-settings
> electron-mocha test

/Users/Shared/x/y/node_modules/electron-settings/node_modules/electron-mocha/index.js:17
var tmpdir = fs.mkdtempSync(path.join(app.getPath('temp'), 'electron-mocha-'))
                                         ^

TypeError: Cannot read property 'getPath' of undefined
    at Object.<anonymous> (/Users/Shared/x/y/node_modules/electron-settings/node_modules/electron-mocha/index.js:17:42)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:402:7)
    at startup (bootstrap_node.js:157:9)
    at bootstrap_node.js:521:3
```

mac OS X yosemite

**Comment by nathanbuchar** [comment]
Which version of Electron are you using?

**Comment by nathanbuchar** [comment]
Electron-settings v3.0.0 released
