### ISSUE TITLE
Cannot read property 'app' of undefined

### ISSUE THREAD

**Issue by black-snow** [nathanbuchar/electron-settings#46]
Having the following error on OS X yosemite (not under windows):

```shell
/Users/Shared/x/y/node_modules/electron-settings/lib/settings.js:23
const app = electron.app || electron.remote.app;
                                           ^

TypeError: Cannot read property 'app' of undefined
    at Object.<anonymous> (/Users/Shared/x/y/node_modules/electron-settings/lib/settings.js:23:44)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)

    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Shared/x/y/node_modules/electron-settings/index.js:17:18)
    at Module._compile (module.js:556:32)
```

This is my code:

```javascript
import settings from 'electron-settings'
// ...
app.on('ready', function () {
    // use settings
}
```

Fails right at the import ... electron 1.4.10
Weird error - seems like your module isn't seeing electron at all.

**Comment by black-snow** [comment]
Weird, seems to be an issue w/ the terminal plugin I use - works with another one.
